const fonts = {
  regular: 'Poppins-Regular', // You can replace this with a custom font if you have one
  bold: 'Poppins-Bold',
  meduim: 'Poppins-Medium',
  semiBold: 'Poppins-SemiBold', // You can replace this with your bold custom font
  light: 'Poppins-Light',
};

const colors = {
  black: '#000000',
  gradient: {
    first: '#F50777',
    second: '#F93E51',
    last: '#FE742B',
  },
  lightGradient: {
    first: 'rgba(245, 7, 119, 0.3)',   // 50% opacity
    second: 'rgba(249, 62, 81, 0.3)',
    last: 'rgba(254, 116, 43, 0.3)',
  },
  orange: '#FE742B',
  grey: '#A1A1A1',
  white: '#ffffff',
  lightGrey: '#E5E5E5',
  mediumGrey: "#666666",
  bordercolor: '#B0B0B0',
  callModalBackground: 'rgba(66, 65, 65, 0.66)',
  callCut: "#FB4F4F",
  callAccept: "#09C26F",
  red: "#FF1616",
  greyLighter: "#E8E8E8BF"


};

export const unmutedIcon = require("../assets/images/mute.png")
export const mutedIcon = require("../assets/images/unmute.png")
export const speakerIcon = require("../assets/images/speaker-disabled.png")
export const unspeakerIcon = require("../assets/images/speaker-enabled.png")


const nativeLanguages = [
  'Albanian',
  'Amharic',
  'Arabic',
  'Armenian',
  'Assamese',
  'Azerbaijani',
  'Basque',
  'Belarusian',
  'Bengali',
  'Bhojpuri',
  'Bulgarian',
  'Burmese',
  'Catalan',
  'Cebuano',
  'Chhattisgarhi',
  'Chittagonian',
  'Czech',
  'Danish',
  'Dutch',
  'English',
  'Estonian',
  'Farsi (Persian)',
  'Finnish',
  'French',
  'Galician',
  'Georgian',
  'German',
  'Greek',
  'Gujarati',
  'Hakka Chinese',
  'Hausa',
  'Hebrew',
  'Hindi',
  'Hmong',
  'Hungarian',
  'Icelandic',
  'Irish Gaelic',
  'Italian',
  'Japanese',
  'Javanese',
  'Jin Chinese',
  'Kannada',
  'Kazakh',
  'Khmer',
  'Korean',
  'Kurdish',
  'Lao',
  'Latvian',
  'Lithuanian',
  'Macedonian',
  'Magahi',
  'Maithili',
  'Malagasy',
  'Malayalam',
  'Mandarin Chinese',
  'Marathi',
  'Nepali',
  'Norwegian',
  'Odia (Oriya)',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Romanian',
  'Russian',
  'Scottish Gaelic',
  'Serbo-Croatian',
  'Shona',
  'Sindhi',
  'Sinhalese',
  'Slovak',
  'Slovenian',
  'Somali',
  'Southern Min Chinese',
  'Spanish',
  'Sundanese',
  'Swahili',
  'Swedish',
  'Tamil',
  'Telugu',
  'Thai',
  'Turkish',
  'Ukrainian',
  'Urdu',
  'Uyghur',
  'Vietnamese',
  'Welsh',
  'Wu Chinese',
  'Yoruba',
  'Zulu',
];

export { fonts, colors, nativeLanguages };
